version: "3"

vars:
  MOUNT_PATH: "/Users/mattiastengbrand/Library/Mobile Documents/com~apple~CloudDocs/Spring/uppland 2/files"

tasks:
  _install-oracle-instantclient:
    desc: "install oracle-instantclient"
    dir: "~/.devbox"
    cmds:
      - mkdir -p oracle_instantclient
      - cd oracle_instantclient
    #  - curl -O https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip
      - unzip -o instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip


  install-oracle-instantclient:
    desc: "install oracle-instantclient"
    dir: "~/.devbox"
    cmds:
      - mkdir -p oracle_instantclient
      - cd oracle_instantclient
      - cp instantclient-basic-linux.x64-19.28.0.0.0dbru.zip .
      - unzip -o instantclient-basic-linux.x64-19.28.0.0.0dbru.zip




      
